# Generated by Django 5.2.6 on 2025-09-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='upload_date',
            new_name='release_date',
        ),
    ]
