# Generated by Django 5.2.6 on 2025-09-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
